// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.robotninjas.barge.proto;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommitOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes client_id = 1;
    /**
     * <code>required bytes client_id = 1;</code>
     */
    boolean hasClientId();
    /**
     * <code>required bytes client_id = 1;</code>
     */
    com.google.protobuf.ByteString getClientId();

    // required int64 sequence = 2;
    /**
     * <code>required int64 sequence = 2;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int64 sequence = 2;</code>
     */
    long getSequence();

    // required bytes op = 3;
    /**
     * <code>required bytes op = 3;</code>
     */
    boolean hasOp();
    /**
     * <code>required bytes op = 3;</code>
     */
    com.google.protobuf.ByteString getOp();
  }
  /**
   * Protobuf type {@code CommitOperation}
   */
  public static final class CommitOperation extends
      com.google.protobuf.GeneratedMessage
      implements CommitOperationOrBuilder {
    // Use CommitOperation.newBuilder() to construct.
    private CommitOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommitOperation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommitOperation defaultInstance;
    public static CommitOperation getDefaultInstance() {
      return defaultInstance;
    }

    public CommitOperation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommitOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequence_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              op_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.ClientProto.CommitOperation.class, org.robotninjas.barge.proto.ClientProto.CommitOperation.Builder.class);
    }

    public static com.google.protobuf.Parser<CommitOperation> PARSER =
        new com.google.protobuf.AbstractParser<CommitOperation>() {
      public CommitOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommitOperation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommitOperation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes client_id = 1;
    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientId_;
    /**
     * <code>required bytes client_id = 1;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes client_id = 1;</code>
     */
    public com.google.protobuf.ByteString getClientId() {
      return clientId_;
    }

    // required int64 sequence = 2;
    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private long sequence_;
    /**
     * <code>required int64 sequence = 2;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 sequence = 2;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    // required bytes op = 3;
    public static final int OP_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString op_;
    /**
     * <code>required bytes op = 3;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes op = 3;</code>
     */
    public com.google.protobuf.ByteString getOp() {
      return op_;
    }

    private void initFields() {
      clientId_ = com.google.protobuf.ByteString.EMPTY;
      sequence_ = 0L;
      op_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, op_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, op_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.ClientProto.CommitOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommitOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.ClientProto.CommitOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.ClientProto.CommitOperation.class, org.robotninjas.barge.proto.ClientProto.CommitOperation.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.ClientProto.CommitOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        op_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperation_descriptor;
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperation getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.ClientProto.CommitOperation.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperation build() {
        org.robotninjas.barge.proto.ClientProto.CommitOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperation buildPartial() {
        org.robotninjas.barge.proto.ClientProto.CommitOperation result = new org.robotninjas.barge.proto.ClientProto.CommitOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.op_ = op_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.ClientProto.CommitOperation) {
          return mergeFrom((org.robotninjas.barge.proto.ClientProto.CommitOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.ClientProto.CommitOperation other) {
        if (other == org.robotninjas.barge.proto.ClientProto.CommitOperation.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasSequence()) {
          
          return false;
        }
        if (!hasOp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.ClientProto.CommitOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.ClientProto.CommitOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes client_id = 1;
      private com.google.protobuf.ByteString clientId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes client_id = 1;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes client_id = 1;</code>
       */
      public com.google.protobuf.ByteString getClientId() {
        return clientId_;
      }
      /**
       * <code>required bytes client_id = 1;</code>
       */
      public Builder setClientId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes client_id = 1;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }

      // required int64 sequence = 2;
      private long sequence_ ;
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000002;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      // required bytes op = 3;
      private com.google.protobuf.ByteString op_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes op = 3;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes op = 3;</code>
       */
      public com.google.protobuf.ByteString getOp() {
        return op_;
      }
      /**
       * <code>required bytes op = 3;</code>
       */
      public Builder setOp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes op = 3;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        op_ = getDefaultInstance().getOp();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CommitOperation)
    }

    static {
      defaultInstance = new CommitOperation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CommitOperation)
  }

  public interface RedirectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string leader_id = 1;
    /**
     * <code>required string leader_id = 1;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required string leader_id = 1;</code>
     */
    java.lang.String getLeaderId();
    /**
     * <code>required string leader_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getLeaderIdBytes();
  }
  /**
   * Protobuf type {@code Redirect}
   */
  public static final class Redirect extends
      com.google.protobuf.GeneratedMessage
      implements RedirectOrBuilder {
    // Use Redirect.newBuilder() to construct.
    private Redirect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Redirect(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Redirect defaultInstance;
    public static Redirect getDefaultInstance() {
      return defaultInstance;
    }

    public Redirect getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Redirect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              leaderId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_Redirect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_Redirect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.ClientProto.Redirect.class, org.robotninjas.barge.proto.ClientProto.Redirect.Builder.class);
    }

    public static com.google.protobuf.Parser<Redirect> PARSER =
        new com.google.protobuf.AbstractParser<Redirect>() {
      public Redirect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Redirect(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Redirect> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string leader_id = 1;
    public static final int LEADER_ID_FIELD_NUMBER = 1;
    private java.lang.Object leaderId_;
    /**
     * <code>required string leader_id = 1;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string leader_id = 1;</code>
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string leader_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      leaderId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLeaderIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLeaderIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.Redirect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.ClientProto.Redirect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Redirect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_Redirect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_Redirect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.ClientProto.Redirect.class, org.robotninjas.barge.proto.ClientProto.Redirect.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.ClientProto.Redirect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        leaderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_Redirect_descriptor;
      }

      public org.robotninjas.barge.proto.ClientProto.Redirect getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.ClientProto.Redirect build() {
        org.robotninjas.barge.proto.ClientProto.Redirect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.ClientProto.Redirect buildPartial() {
        org.robotninjas.barge.proto.ClientProto.Redirect result = new org.robotninjas.barge.proto.ClientProto.Redirect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.leaderId_ = leaderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.ClientProto.Redirect) {
          return mergeFrom((org.robotninjas.barge.proto.ClientProto.Redirect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.ClientProto.Redirect other) {
        if (other == org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance()) return this;
        if (other.hasLeaderId()) {
          bitField0_ |= 0x00000001;
          leaderId_ = other.leaderId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLeaderId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.ClientProto.Redirect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.ClientProto.Redirect) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string leader_id = 1;
      private java.lang.Object leaderId_ = "";
      /**
       * <code>required string leader_id = 1;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string leader_id = 1;</code>
       */
      public java.lang.String getLeaderId() {
        java.lang.Object ref = leaderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          leaderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string leader_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderIdBytes() {
        java.lang.Object ref = leaderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string leader_id = 1;</code>
       */
      public Builder setLeaderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string leader_id = 1;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = getDefaultInstance().getLeaderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string leader_id = 1;</code>
       */
      public Builder setLeaderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        leaderId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Redirect)
    }

    static {
      defaultInstance = new Redirect(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Redirect)
  }

  public interface CommitOperationResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool committed = 1;
    /**
     * <code>required bool committed = 1;</code>
     */
    boolean hasCommitted();
    /**
     * <code>required bool committed = 1;</code>
     */
    boolean getCommitted();

    // optional .CommitOperationResponse.ErrorCode error_code = 2;
    /**
     * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
     */
    org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode getErrorCode();

    // optional .Redirect redirect = 3;
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    boolean hasRedirect();
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    org.robotninjas.barge.proto.ClientProto.Redirect getRedirect();
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder getRedirectOrBuilder();

    // repeated string cluster_members = 4;
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    java.util.List<java.lang.String>
    getClusterMembersList();
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    int getClusterMembersCount();
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    java.lang.String getClusterMembers(int index);
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    com.google.protobuf.ByteString
        getClusterMembersBytes(int index);
  }
  /**
   * Protobuf type {@code CommitOperationResponse}
   */
  public static final class CommitOperationResponse extends
      com.google.protobuf.GeneratedMessage
      implements CommitOperationResponseOrBuilder {
    // Use CommitOperationResponse.newBuilder() to construct.
    private CommitOperationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommitOperationResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommitOperationResponse defaultInstance;
    public static CommitOperationResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CommitOperationResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommitOperationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              committed_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode value = org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                errorCode_ = value;
              }
              break;
            }
            case 26: {
              org.robotninjas.barge.proto.ClientProto.Redirect.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = redirect_.toBuilder();
              }
              redirect_ = input.readMessage(org.robotninjas.barge.proto.ClientProto.Redirect.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(redirect_);
                redirect_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                clusterMembers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              clusterMembers_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          clusterMembers_ = new com.google.protobuf.UnmodifiableLazyStringList(clusterMembers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.class, org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CommitOperationResponse> PARSER =
        new com.google.protobuf.AbstractParser<CommitOperationResponse>() {
      public CommitOperationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommitOperationResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommitOperationResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code CommitOperationResponse.ErrorCode}
     */
    public enum ErrorCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOLEADER = 2;</code>
       */
      NOLEADER(0, 2),
      ;

      /**
       * <code>NOLEADER = 2;</code>
       */
      public static final int NOLEADER_VALUE = 2;


      public final int getNumber() { return value; }

      public static ErrorCode valueOf(int value) {
        switch (value) {
          case 2: return NOLEADER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
              public ErrorCode findValueByNumber(int number) {
                return ErrorCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ErrorCode[] VALUES = values();

      public static ErrorCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ErrorCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CommitOperationResponse.ErrorCode)
    }

    private int bitField0_;
    // required bool committed = 1;
    public static final int COMMITTED_FIELD_NUMBER = 1;
    private boolean committed_;
    /**
     * <code>required bool committed = 1;</code>
     */
    public boolean hasCommitted() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool committed = 1;</code>
     */
    public boolean getCommitted() {
      return committed_;
    }

    // optional .CommitOperationResponse.ErrorCode error_code = 2;
    public static final int ERROR_CODE_FIELD_NUMBER = 2;
    private org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode errorCode_;
    /**
     * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
     */
    public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode getErrorCode() {
      return errorCode_;
    }

    // optional .Redirect redirect = 3;
    public static final int REDIRECT_FIELD_NUMBER = 3;
    private org.robotninjas.barge.proto.ClientProto.Redirect redirect_;
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    public boolean hasRedirect() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    public org.robotninjas.barge.proto.ClientProto.Redirect getRedirect() {
      return redirect_;
    }
    /**
     * <code>optional .Redirect redirect = 3;</code>
     */
    public org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder getRedirectOrBuilder() {
      return redirect_;
    }

    // repeated string cluster_members = 4;
    public static final int CLUSTER_MEMBERS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList clusterMembers_;
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    public java.util.List<java.lang.String>
        getClusterMembersList() {
      return clusterMembers_;
    }
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    public int getClusterMembersCount() {
      return clusterMembers_.size();
    }
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    public java.lang.String getClusterMembers(int index) {
      return clusterMembers_.get(index);
    }
    /**
     * <code>repeated string cluster_members = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClusterMembersBytes(int index) {
      return clusterMembers_.getByteString(index);
    }

    private void initFields() {
      committed_ = false;
      errorCode_ = org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode.NOLEADER;
      redirect_ = org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance();
      clusterMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommitted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRedirect()) {
        if (!getRedirect().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, committed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, redirect_);
      }
      for (int i = 0; i < clusterMembers_.size(); i++) {
        output.writeBytes(4, clusterMembers_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, committed_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, redirect_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clusterMembers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(clusterMembers_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClusterMembersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.ClientProto.CommitOperationResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommitOperationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.ClientProto.CommitOperationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperationResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.class, org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRedirectFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        committed_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode.NOLEADER;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (redirectBuilder_ == null) {
          redirect_ = org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance();
        } else {
          redirectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        clusterMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.ClientProto.internal_static_CommitOperationResponse_descriptor;
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse build() {
        org.robotninjas.barge.proto.ClientProto.CommitOperationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse buildPartial() {
        org.robotninjas.barge.proto.ClientProto.CommitOperationResponse result = new org.robotninjas.barge.proto.ClientProto.CommitOperationResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.committed_ = committed_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (redirectBuilder_ == null) {
          result.redirect_ = redirect_;
        } else {
          result.redirect_ = redirectBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          clusterMembers_ = new com.google.protobuf.UnmodifiableLazyStringList(
              clusterMembers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.clusterMembers_ = clusterMembers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.ClientProto.CommitOperationResponse) {
          return mergeFrom((org.robotninjas.barge.proto.ClientProto.CommitOperationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.ClientProto.CommitOperationResponse other) {
        if (other == org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance()) return this;
        if (other.hasCommitted()) {
          setCommitted(other.getCommitted());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRedirect()) {
          mergeRedirect(other.getRedirect());
        }
        if (!other.clusterMembers_.isEmpty()) {
          if (clusterMembers_.isEmpty()) {
            clusterMembers_ = other.clusterMembers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureClusterMembersIsMutable();
            clusterMembers_.addAll(other.clusterMembers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommitted()) {
          
          return false;
        }
        if (hasRedirect()) {
          if (!getRedirect().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.ClientProto.CommitOperationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.ClientProto.CommitOperationResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool committed = 1;
      private boolean committed_ ;
      /**
       * <code>required bool committed = 1;</code>
       */
      public boolean hasCommitted() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool committed = 1;</code>
       */
      public boolean getCommitted() {
        return committed_;
      }
      /**
       * <code>required bool committed = 1;</code>
       */
      public Builder setCommitted(boolean value) {
        bitField0_ |= 0x00000001;
        committed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool committed = 1;</code>
       */
      public Builder clearCommitted() {
        bitField0_ = (bitField0_ & ~0x00000001);
        committed_ = false;
        onChanged();
        return this;
      }

      // optional .CommitOperationResponse.ErrorCode error_code = 2;
      private org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode errorCode_ = org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode.NOLEADER;
      /**
       * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
       */
      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
       */
      public Builder setErrorCode(org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CommitOperationResponse.ErrorCode error_code = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.ErrorCode.NOLEADER;
        onChanged();
        return this;
      }

      // optional .Redirect redirect = 3;
      private org.robotninjas.barge.proto.ClientProto.Redirect redirect_ = org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.ClientProto.Redirect, org.robotninjas.barge.proto.ClientProto.Redirect.Builder, org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder> redirectBuilder_;
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public boolean hasRedirect() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public org.robotninjas.barge.proto.ClientProto.Redirect getRedirect() {
        if (redirectBuilder_ == null) {
          return redirect_;
        } else {
          return redirectBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public Builder setRedirect(org.robotninjas.barge.proto.ClientProto.Redirect value) {
        if (redirectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          redirect_ = value;
          onChanged();
        } else {
          redirectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public Builder setRedirect(
          org.robotninjas.barge.proto.ClientProto.Redirect.Builder builderForValue) {
        if (redirectBuilder_ == null) {
          redirect_ = builderForValue.build();
          onChanged();
        } else {
          redirectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public Builder mergeRedirect(org.robotninjas.barge.proto.ClientProto.Redirect value) {
        if (redirectBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              redirect_ != org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance()) {
            redirect_ =
              org.robotninjas.barge.proto.ClientProto.Redirect.newBuilder(redirect_).mergeFrom(value).buildPartial();
          } else {
            redirect_ = value;
          }
          onChanged();
        } else {
          redirectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public Builder clearRedirect() {
        if (redirectBuilder_ == null) {
          redirect_ = org.robotninjas.barge.proto.ClientProto.Redirect.getDefaultInstance();
          onChanged();
        } else {
          redirectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public org.robotninjas.barge.proto.ClientProto.Redirect.Builder getRedirectBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRedirectFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      public org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder getRedirectOrBuilder() {
        if (redirectBuilder_ != null) {
          return redirectBuilder_.getMessageOrBuilder();
        } else {
          return redirect_;
        }
      }
      /**
       * <code>optional .Redirect redirect = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.ClientProto.Redirect, org.robotninjas.barge.proto.ClientProto.Redirect.Builder, org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder> 
          getRedirectFieldBuilder() {
        if (redirectBuilder_ == null) {
          redirectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robotninjas.barge.proto.ClientProto.Redirect, org.robotninjas.barge.proto.ClientProto.Redirect.Builder, org.robotninjas.barge.proto.ClientProto.RedirectOrBuilder>(
                  redirect_,
                  getParentForChildren(),
                  isClean());
          redirect_ = null;
        }
        return redirectBuilder_;
      }

      // repeated string cluster_members = 4;
      private com.google.protobuf.LazyStringList clusterMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClusterMembersIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          clusterMembers_ = new com.google.protobuf.LazyStringArrayList(clusterMembers_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public java.util.List<java.lang.String>
          getClusterMembersList() {
        return java.util.Collections.unmodifiableList(clusterMembers_);
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public int getClusterMembersCount() {
        return clusterMembers_.size();
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public java.lang.String getClusterMembers(int index) {
        return clusterMembers_.get(index);
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClusterMembersBytes(int index) {
        return clusterMembers_.getByteString(index);
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public Builder setClusterMembers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClusterMembersIsMutable();
        clusterMembers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public Builder addClusterMembers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClusterMembersIsMutable();
        clusterMembers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public Builder addAllClusterMembers(
          java.lang.Iterable<java.lang.String> values) {
        ensureClusterMembersIsMutable();
        super.addAll(values, clusterMembers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public Builder clearClusterMembers() {
        clusterMembers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cluster_members = 4;</code>
       */
      public Builder addClusterMembersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClusterMembersIsMutable();
        clusterMembers_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CommitOperationResponse)
    }

    static {
      defaultInstance = new CommitOperationResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CommitOperationResponse)
  }

  /**
   * Protobuf service {@code ClientService}
   */
  public static abstract class ClientService
      implements com.google.protobuf.Service {
    protected ClientService() {}

    public interface Interface {
      /**
       * <code>rpc commitOperation(.CommitOperation) returns (.CommitOperationResponse);</code>
       */
      public abstract void commitOperation(
          com.google.protobuf.RpcController controller,
          org.robotninjas.barge.proto.ClientProto.CommitOperation request,
          com.google.protobuf.RpcCallback<org.robotninjas.barge.proto.ClientProto.CommitOperationResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ClientService() {
        @java.lang.Override
        public  void commitOperation(
            com.google.protobuf.RpcController controller,
            org.robotninjas.barge.proto.ClientProto.CommitOperation request,
            com.google.protobuf.RpcCallback<org.robotninjas.barge.proto.ClientProto.CommitOperationResponse> done) {
          impl.commitOperation(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.commitOperation(controller, (org.robotninjas.barge.proto.ClientProto.CommitOperation)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.robotninjas.barge.proto.ClientProto.CommitOperation.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc commitOperation(.CommitOperation) returns (.CommitOperationResponse);</code>
     */
    public abstract void commitOperation(
        com.google.protobuf.RpcController controller,
        org.robotninjas.barge.proto.ClientProto.CommitOperation request,
        com.google.protobuf.RpcCallback<org.robotninjas.barge.proto.ClientProto.CommitOperationResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.ClientProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.commitOperation(controller, (org.robotninjas.barge.proto.ClientProto.CommitOperation)request,
            com.google.protobuf.RpcUtil.<org.robotninjas.barge.proto.ClientProto.CommitOperationResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.robotninjas.barge.proto.ClientProto.CommitOperation.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.robotninjas.barge.proto.ClientProto.ClientService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void commitOperation(
          com.google.protobuf.RpcController controller,
          org.robotninjas.barge.proto.ClientProto.CommitOperation request,
          com.google.protobuf.RpcCallback<org.robotninjas.barge.proto.ClientProto.CommitOperationResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.class,
            org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse commitOperation(
          com.google.protobuf.RpcController controller,
          org.robotninjas.barge.proto.ClientProto.CommitOperation request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.robotninjas.barge.proto.ClientProto.CommitOperationResponse commitOperation(
          com.google.protobuf.RpcController controller,
          org.robotninjas.barge.proto.ClientProto.CommitOperation request)
          throws com.google.protobuf.ServiceException {
        return (org.robotninjas.barge.proto.ClientProto.CommitOperationResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.robotninjas.barge.proto.ClientProto.CommitOperationResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ClientService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommitOperation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Redirect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Redirect_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitOperationResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommitOperationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\032\013entry.proto\"B\n\017CommitOpe" +
      "ration\022\021\n\tclient_id\030\001 \002(\014\022\020\n\010sequence\030\002 " +
      "\002(\003\022\n\n\002op\030\003 \002(\014\"\035\n\010Redirect\022\021\n\tleader_id" +
      "\030\001 \002(\t\"\265\001\n\027CommitOperationResponse\022\021\n\tco" +
      "mmitted\030\001 \002(\010\0226\n\nerror_code\030\002 \001(\0162\".Comm" +
      "itOperationResponse.ErrorCode\022\033\n\010redirec" +
      "t\030\003 \001(\0132\t.Redirect\022\027\n\017cluster_members\030\004 " +
      "\003(\t\"\031\n\tErrorCode\022\014\n\010NOLEADER\020\0022N\n\rClient" +
      "Service\022=\n\017commitOperation\022\020.CommitOpera" +
      "tion\032\030.CommitOperationResponseB-\n\033org.ro",
      "botninjas.barge.protoB\013ClientProto\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CommitOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CommitOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CommitOperation_descriptor,
              new java.lang.String[] { "ClientId", "Sequence", "Op", });
          internal_static_Redirect_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Redirect_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Redirect_descriptor,
              new java.lang.String[] { "LeaderId", });
          internal_static_CommitOperationResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CommitOperationResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CommitOperationResponse_descriptor,
              new java.lang.String[] { "Committed", "ErrorCode", "Redirect", "ClusterMembers", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robotninjas.barge.proto.RaftEntry.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
