// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

package org.robotninjas.barge.proto;

public final class LogProto {
  private LogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppendOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 index = 1;
    /**
     * <code>required int64 index = 1;</code>
     */
    boolean hasIndex();
    /**
     * <code>required int64 index = 1;</code>
     */
    long getIndex();

    // required .Entry entry = 2;
    /**
     * <code>required .Entry entry = 2;</code>
     */
    boolean hasEntry();
    /**
     * <code>required .Entry entry = 2;</code>
     */
    org.robotninjas.barge.proto.RaftEntry.Entry getEntry();
    /**
     * <code>required .Entry entry = 2;</code>
     */
    org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder getEntryOrBuilder();
  }
  /**
   * Protobuf type {@code Append}
   */
  public static final class Append extends
      com.google.protobuf.GeneratedMessage
      implements AppendOrBuilder {
    // Use Append.newBuilder() to construct.
    private Append(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Append(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Append defaultInstance;
    public static Append getDefaultInstance() {
      return defaultInstance;
    }

    public Append getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Append(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              index_ = input.readInt64();
              break;
            }
            case 18: {
              org.robotninjas.barge.proto.RaftEntry.Entry.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = entry_.toBuilder();
              }
              entry_ = input.readMessage(org.robotninjas.barge.proto.RaftEntry.Entry.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(entry_);
                entry_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.LogProto.internal_static_Append_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.LogProto.internal_static_Append_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.LogProto.Append.class, org.robotninjas.barge.proto.LogProto.Append.Builder.class);
    }

    public static com.google.protobuf.Parser<Append> PARSER =
        new com.google.protobuf.AbstractParser<Append>() {
      public Append parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Append(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Append> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>required int64 index = 1;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 index = 1;</code>
     */
    public long getIndex() {
      return index_;
    }

    // required .Entry entry = 2;
    public static final int ENTRY_FIELD_NUMBER = 2;
    private org.robotninjas.barge.proto.RaftEntry.Entry entry_;
    /**
     * <code>required .Entry entry = 2;</code>
     */
    public boolean hasEntry() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Entry entry = 2;</code>
     */
    public org.robotninjas.barge.proto.RaftEntry.Entry getEntry() {
      return entry_;
    }
    /**
     * <code>required .Entry entry = 2;</code>
     */
    public org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder getEntryOrBuilder() {
      return entry_;
    }

    private void initFields() {
      index_ = 0L;
      entry_ = org.robotninjas.barge.proto.RaftEntry.Entry.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEntry().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, entry_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, entry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Append parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.LogProto.Append prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Append}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.LogProto.AppendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Append_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Append_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.LogProto.Append.class, org.robotninjas.barge.proto.LogProto.Append.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.LogProto.Append.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        index_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (entryBuilder_ == null) {
          entry_ = org.robotninjas.barge.proto.RaftEntry.Entry.getDefaultInstance();
        } else {
          entryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Append_descriptor;
      }

      public org.robotninjas.barge.proto.LogProto.Append getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.LogProto.Append build() {
        org.robotninjas.barge.proto.LogProto.Append result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.LogProto.Append buildPartial() {
        org.robotninjas.barge.proto.LogProto.Append result = new org.robotninjas.barge.proto.LogProto.Append(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (entryBuilder_ == null) {
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.LogProto.Append) {
          return mergeFrom((org.robotninjas.barge.proto.LogProto.Append)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.LogProto.Append other) {
        if (other == org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasEntry()) {
          mergeEntry(other.getEntry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIndex()) {
          
          return false;
        }
        if (!hasEntry()) {
          
          return false;
        }
        if (!getEntry().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.LogProto.Append parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.LogProto.Append) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 index = 1;
      private long index_ ;
      /**
       * <code>required int64 index = 1;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public Builder setIndex(long value) {
        bitField0_ |= 0x00000001;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0L;
        onChanged();
        return this;
      }

      // required .Entry entry = 2;
      private org.robotninjas.barge.proto.RaftEntry.Entry entry_ = org.robotninjas.barge.proto.RaftEntry.Entry.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.RaftEntry.Entry, org.robotninjas.barge.proto.RaftEntry.Entry.Builder, org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder> entryBuilder_;
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public boolean hasEntry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public org.robotninjas.barge.proto.RaftEntry.Entry getEntry() {
        if (entryBuilder_ == null) {
          return entry_;
        } else {
          return entryBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public Builder setEntry(org.robotninjas.barge.proto.RaftEntry.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entry_ = value;
          onChanged();
        } else {
          entryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public Builder setEntry(
          org.robotninjas.barge.proto.RaftEntry.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          entry_ = builderForValue.build();
          onChanged();
        } else {
          entryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public Builder mergeEntry(org.robotninjas.barge.proto.RaftEntry.Entry value) {
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              entry_ != org.robotninjas.barge.proto.RaftEntry.Entry.getDefaultInstance()) {
            entry_ =
              org.robotninjas.barge.proto.RaftEntry.Entry.newBuilder(entry_).mergeFrom(value).buildPartial();
          } else {
            entry_ = value;
          }
          onChanged();
        } else {
          entryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = org.robotninjas.barge.proto.RaftEntry.Entry.getDefaultInstance();
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public org.robotninjas.barge.proto.RaftEntry.Entry.Builder getEntryBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEntryFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      public org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder getEntryOrBuilder() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilder();
        } else {
          return entry_;
        }
      }
      /**
       * <code>required .Entry entry = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.RaftEntry.Entry, org.robotninjas.barge.proto.RaftEntry.Entry.Builder, org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robotninjas.barge.proto.RaftEntry.Entry, org.robotninjas.barge.proto.RaftEntry.Entry.Builder, org.robotninjas.barge.proto.RaftEntry.EntryOrBuilder>(
                  entry_,
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Append)
    }

    static {
      defaultInstance = new Append(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Append)
  }

  public interface MembershipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 index = 1;
    /**
     * <code>required int64 index = 1;</code>
     */
    boolean hasIndex();
    /**
     * <code>required int64 index = 1;</code>
     */
    long getIndex();

    // required int64 term = 2;
    /**
     * <code>required int64 term = 2;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int64 term = 2;</code>
     */
    long getTerm();

    // repeated string members = 3;
    /**
     * <code>repeated string members = 3;</code>
     */
    java.util.List<java.lang.String>
    getMembersList();
    /**
     * <code>repeated string members = 3;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated string members = 3;</code>
     */
    java.lang.String getMembers(int index);
    /**
     * <code>repeated string members = 3;</code>
     */
    com.google.protobuf.ByteString
        getMembersBytes(int index);
  }
  /**
   * Protobuf type {@code Membership}
   */
  public static final class Membership extends
      com.google.protobuf.GeneratedMessage
      implements MembershipOrBuilder {
    // Use Membership.newBuilder() to construct.
    private Membership(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Membership(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Membership defaultInstance;
    public static Membership getDefaultInstance() {
      return defaultInstance;
    }

    public Membership getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Membership(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              index_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              term_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                members_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              members_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = new com.google.protobuf.UnmodifiableLazyStringList(members_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.LogProto.internal_static_Membership_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.LogProto.internal_static_Membership_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.LogProto.Membership.class, org.robotninjas.barge.proto.LogProto.Membership.Builder.class);
    }

    public static com.google.protobuf.Parser<Membership> PARSER =
        new com.google.protobuf.AbstractParser<Membership>() {
      public Membership parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Membership(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Membership> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>required int64 index = 1;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 index = 1;</code>
     */
    public long getIndex() {
      return index_;
    }

    // required int64 term = 2;
    public static final int TERM_FIELD_NUMBER = 2;
    private long term_;
    /**
     * <code>required int64 term = 2;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 term = 2;</code>
     */
    public long getTerm() {
      return term_;
    }

    // repeated string members = 3;
    public static final int MEMBERS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList members_;
    /**
     * <code>repeated string members = 3;</code>
     */
    public java.util.List<java.lang.String>
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated string members = 3;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated string members = 3;</code>
     */
    public java.lang.String getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated string members = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMembersBytes(int index) {
      return members_.getByteString(index);
    }

    private void initFields() {
      index_ = 0L;
      term_ = 0L;
      members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, term_);
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeBytes(3, members_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, term_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(members_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMembersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.Membership parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.LogProto.Membership prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Membership}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.LogProto.MembershipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Membership_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Membership_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.LogProto.Membership.class, org.robotninjas.barge.proto.LogProto.Membership.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.LogProto.Membership.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        index_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.LogProto.internal_static_Membership_descriptor;
      }

      public org.robotninjas.barge.proto.LogProto.Membership getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.LogProto.Membership build() {
        org.robotninjas.barge.proto.LogProto.Membership result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.LogProto.Membership buildPartial() {
        org.robotninjas.barge.proto.LogProto.Membership result = new org.robotninjas.barge.proto.LogProto.Membership(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.term_ = term_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = new com.google.protobuf.UnmodifiableLazyStringList(
              members_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.members_ = members_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.LogProto.Membership) {
          return mergeFrom((org.robotninjas.barge.proto.LogProto.Membership)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.LogProto.Membership other) {
        if (other == org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIndex()) {
          
          return false;
        }
        if (!hasTerm()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.LogProto.Membership parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.LogProto.Membership) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 index = 1;
      private long index_ ;
      /**
       * <code>required int64 index = 1;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public Builder setIndex(long value) {
        bitField0_ |= 0x00000001;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 index = 1;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0L;
        onChanged();
        return this;
      }

      // required int64 term = 2;
      private long term_ ;
      /**
       * <code>required int64 term = 2;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 term = 2;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>required int64 term = 2;</code>
       */
      public Builder setTerm(long value) {
        bitField0_ |= 0x00000002;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 term = 2;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0L;
        onChanged();
        return this;
      }

      // repeated string members = 3;
      private com.google.protobuf.LazyStringList members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = new com.google.protobuf.LazyStringArrayList(members_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public java.util.List<java.lang.String>
          getMembersList() {
        return java.util.Collections.unmodifiableList(members_);
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public java.lang.String getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMembersBytes(int index) {
        return members_.getByteString(index);
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public Builder setMembers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public Builder addMembers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public Builder addAllMembers(
          java.lang.Iterable<java.lang.String> values) {
        ensureMembersIsMutable();
        super.addAll(values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public Builder clearMembers() {
        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 3;</code>
       */
      public Builder addMembersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Membership)
    }

    static {
      defaultInstance = new Membership(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Membership)
  }

  public interface JournalEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .JournalEntry.Type type = 1;
    /**
     * <code>required .JournalEntry.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .JournalEntry.Type type = 1;</code>
     */
    org.robotninjas.barge.proto.LogProto.JournalEntry.Type getType();

    // optional .Append append = 2;
    /**
     * <code>optional .Append append = 2;</code>
     */
    boolean hasAppend();
    /**
     * <code>optional .Append append = 2;</code>
     */
    org.robotninjas.barge.proto.LogProto.Append getAppend();
    /**
     * <code>optional .Append append = 2;</code>
     */
    org.robotninjas.barge.proto.LogProto.AppendOrBuilder getAppendOrBuilder();

    // optional .Membership membership = 3;
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    boolean hasMembership();
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    org.robotninjas.barge.proto.LogProto.Membership getMembership();
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    org.robotninjas.barge.proto.LogProto.MembershipOrBuilder getMembershipOrBuilder();
  }
  /**
   * Protobuf type {@code JournalEntry}
   */
  public static final class JournalEntry extends
      com.google.protobuf.GeneratedMessage
      implements JournalEntryOrBuilder {
    // Use JournalEntry.newBuilder() to construct.
    private JournalEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JournalEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JournalEntry defaultInstance;
    public static JournalEntry getDefaultInstance() {
      return defaultInstance;
    }

    public JournalEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JournalEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.robotninjas.barge.proto.LogProto.JournalEntry.Type value = org.robotninjas.barge.proto.LogProto.JournalEntry.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              org.robotninjas.barge.proto.LogProto.Append.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = append_.toBuilder();
              }
              append_ = input.readMessage(org.robotninjas.barge.proto.LogProto.Append.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(append_);
                append_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.robotninjas.barge.proto.LogProto.Membership.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = membership_.toBuilder();
              }
              membership_ = input.readMessage(org.robotninjas.barge.proto.LogProto.Membership.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(membership_);
                membership_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robotninjas.barge.proto.LogProto.internal_static_JournalEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robotninjas.barge.proto.LogProto.internal_static_JournalEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robotninjas.barge.proto.LogProto.JournalEntry.class, org.robotninjas.barge.proto.LogProto.JournalEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<JournalEntry> PARSER =
        new com.google.protobuf.AbstractParser<JournalEntry>() {
      public JournalEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JournalEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JournalEntry> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code JournalEntry.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>APPEND = 1;</code>
       */
      APPEND(0, 1),
      /**
       * <code>MEMBERSHIP = 2;</code>
       */
      MEMBERSHIP(1, 2),
      ;

      /**
       * <code>APPEND = 1;</code>
       */
      public static final int APPEND_VALUE = 1;
      /**
       * <code>MEMBERSHIP = 2;</code>
       */
      public static final int MEMBERSHIP_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return APPEND;
          case 2: return MEMBERSHIP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.LogProto.JournalEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:JournalEntry.Type)
    }

    private int bitField0_;
    // required .JournalEntry.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.robotninjas.barge.proto.LogProto.JournalEntry.Type type_;
    /**
     * <code>required .JournalEntry.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .JournalEntry.Type type = 1;</code>
     */
    public org.robotninjas.barge.proto.LogProto.JournalEntry.Type getType() {
      return type_;
    }

    // optional .Append append = 2;
    public static final int APPEND_FIELD_NUMBER = 2;
    private org.robotninjas.barge.proto.LogProto.Append append_;
    /**
     * <code>optional .Append append = 2;</code>
     */
    public boolean hasAppend() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Append append = 2;</code>
     */
    public org.robotninjas.barge.proto.LogProto.Append getAppend() {
      return append_;
    }
    /**
     * <code>optional .Append append = 2;</code>
     */
    public org.robotninjas.barge.proto.LogProto.AppendOrBuilder getAppendOrBuilder() {
      return append_;
    }

    // optional .Membership membership = 3;
    public static final int MEMBERSHIP_FIELD_NUMBER = 3;
    private org.robotninjas.barge.proto.LogProto.Membership membership_;
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    public boolean hasMembership() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    public org.robotninjas.barge.proto.LogProto.Membership getMembership() {
      return membership_;
    }
    /**
     * <code>optional .Membership membership = 3;</code>
     */
    public org.robotninjas.barge.proto.LogProto.MembershipOrBuilder getMembershipOrBuilder() {
      return membership_;
    }

    private void initFields() {
      type_ = org.robotninjas.barge.proto.LogProto.JournalEntry.Type.APPEND;
      append_ = org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance();
      membership_ = org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAppend()) {
        if (!getAppend().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMembership()) {
        if (!getMembership().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, append_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, membership_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, append_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, membership_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robotninjas.barge.proto.LogProto.JournalEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robotninjas.barge.proto.LogProto.JournalEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JournalEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robotninjas.barge.proto.LogProto.JournalEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robotninjas.barge.proto.LogProto.internal_static_JournalEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robotninjas.barge.proto.LogProto.internal_static_JournalEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robotninjas.barge.proto.LogProto.JournalEntry.class, org.robotninjas.barge.proto.LogProto.JournalEntry.Builder.class);
      }

      // Construct using org.robotninjas.barge.proto.LogProto.JournalEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppendFieldBuilder();
          getMembershipFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.robotninjas.barge.proto.LogProto.JournalEntry.Type.APPEND;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (appendBuilder_ == null) {
          append_ = org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance();
        } else {
          appendBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (membershipBuilder_ == null) {
          membership_ = org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance();
        } else {
          membershipBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robotninjas.barge.proto.LogProto.internal_static_JournalEntry_descriptor;
      }

      public org.robotninjas.barge.proto.LogProto.JournalEntry getDefaultInstanceForType() {
        return org.robotninjas.barge.proto.LogProto.JournalEntry.getDefaultInstance();
      }

      public org.robotninjas.barge.proto.LogProto.JournalEntry build() {
        org.robotninjas.barge.proto.LogProto.JournalEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robotninjas.barge.proto.LogProto.JournalEntry buildPartial() {
        org.robotninjas.barge.proto.LogProto.JournalEntry result = new org.robotninjas.barge.proto.LogProto.JournalEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (appendBuilder_ == null) {
          result.append_ = append_;
        } else {
          result.append_ = appendBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (membershipBuilder_ == null) {
          result.membership_ = membership_;
        } else {
          result.membership_ = membershipBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robotninjas.barge.proto.LogProto.JournalEntry) {
          return mergeFrom((org.robotninjas.barge.proto.LogProto.JournalEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robotninjas.barge.proto.LogProto.JournalEntry other) {
        if (other == org.robotninjas.barge.proto.LogProto.JournalEntry.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAppend()) {
          mergeAppend(other.getAppend());
        }
        if (other.hasMembership()) {
          mergeMembership(other.getMembership());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasAppend()) {
          if (!getAppend().isInitialized()) {
            
            return false;
          }
        }
        if (hasMembership()) {
          if (!getMembership().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robotninjas.barge.proto.LogProto.JournalEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robotninjas.barge.proto.LogProto.JournalEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .JournalEntry.Type type = 1;
      private org.robotninjas.barge.proto.LogProto.JournalEntry.Type type_ = org.robotninjas.barge.proto.LogProto.JournalEntry.Type.APPEND;
      /**
       * <code>required .JournalEntry.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .JournalEntry.Type type = 1;</code>
       */
      public org.robotninjas.barge.proto.LogProto.JournalEntry.Type getType() {
        return type_;
      }
      /**
       * <code>required .JournalEntry.Type type = 1;</code>
       */
      public Builder setType(org.robotninjas.barge.proto.LogProto.JournalEntry.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .JournalEntry.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.robotninjas.barge.proto.LogProto.JournalEntry.Type.APPEND;
        onChanged();
        return this;
      }

      // optional .Append append = 2;
      private org.robotninjas.barge.proto.LogProto.Append append_ = org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.LogProto.Append, org.robotninjas.barge.proto.LogProto.Append.Builder, org.robotninjas.barge.proto.LogProto.AppendOrBuilder> appendBuilder_;
      /**
       * <code>optional .Append append = 2;</code>
       */
      public boolean hasAppend() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public org.robotninjas.barge.proto.LogProto.Append getAppend() {
        if (appendBuilder_ == null) {
          return append_;
        } else {
          return appendBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public Builder setAppend(org.robotninjas.barge.proto.LogProto.Append value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          append_ = value;
          onChanged();
        } else {
          appendBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public Builder setAppend(
          org.robotninjas.barge.proto.LogProto.Append.Builder builderForValue) {
        if (appendBuilder_ == null) {
          append_ = builderForValue.build();
          onChanged();
        } else {
          appendBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public Builder mergeAppend(org.robotninjas.barge.proto.LogProto.Append value) {
        if (appendBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              append_ != org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance()) {
            append_ =
              org.robotninjas.barge.proto.LogProto.Append.newBuilder(append_).mergeFrom(value).buildPartial();
          } else {
            append_ = value;
          }
          onChanged();
        } else {
          appendBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public Builder clearAppend() {
        if (appendBuilder_ == null) {
          append_ = org.robotninjas.barge.proto.LogProto.Append.getDefaultInstance();
          onChanged();
        } else {
          appendBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public org.robotninjas.barge.proto.LogProto.Append.Builder getAppendBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAppendFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      public org.robotninjas.barge.proto.LogProto.AppendOrBuilder getAppendOrBuilder() {
        if (appendBuilder_ != null) {
          return appendBuilder_.getMessageOrBuilder();
        } else {
          return append_;
        }
      }
      /**
       * <code>optional .Append append = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.LogProto.Append, org.robotninjas.barge.proto.LogProto.Append.Builder, org.robotninjas.barge.proto.LogProto.AppendOrBuilder> 
          getAppendFieldBuilder() {
        if (appendBuilder_ == null) {
          appendBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robotninjas.barge.proto.LogProto.Append, org.robotninjas.barge.proto.LogProto.Append.Builder, org.robotninjas.barge.proto.LogProto.AppendOrBuilder>(
                  append_,
                  getParentForChildren(),
                  isClean());
          append_ = null;
        }
        return appendBuilder_;
      }

      // optional .Membership membership = 3;
      private org.robotninjas.barge.proto.LogProto.Membership membership_ = org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.LogProto.Membership, org.robotninjas.barge.proto.LogProto.Membership.Builder, org.robotninjas.barge.proto.LogProto.MembershipOrBuilder> membershipBuilder_;
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public boolean hasMembership() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public org.robotninjas.barge.proto.LogProto.Membership getMembership() {
        if (membershipBuilder_ == null) {
          return membership_;
        } else {
          return membershipBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public Builder setMembership(org.robotninjas.barge.proto.LogProto.Membership value) {
        if (membershipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          membership_ = value;
          onChanged();
        } else {
          membershipBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public Builder setMembership(
          org.robotninjas.barge.proto.LogProto.Membership.Builder builderForValue) {
        if (membershipBuilder_ == null) {
          membership_ = builderForValue.build();
          onChanged();
        } else {
          membershipBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public Builder mergeMembership(org.robotninjas.barge.proto.LogProto.Membership value) {
        if (membershipBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              membership_ != org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance()) {
            membership_ =
              org.robotninjas.barge.proto.LogProto.Membership.newBuilder(membership_).mergeFrom(value).buildPartial();
          } else {
            membership_ = value;
          }
          onChanged();
        } else {
          membershipBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public Builder clearMembership() {
        if (membershipBuilder_ == null) {
          membership_ = org.robotninjas.barge.proto.LogProto.Membership.getDefaultInstance();
          onChanged();
        } else {
          membershipBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public org.robotninjas.barge.proto.LogProto.Membership.Builder getMembershipBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMembershipFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      public org.robotninjas.barge.proto.LogProto.MembershipOrBuilder getMembershipOrBuilder() {
        if (membershipBuilder_ != null) {
          return membershipBuilder_.getMessageOrBuilder();
        } else {
          return membership_;
        }
      }
      /**
       * <code>optional .Membership membership = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.robotninjas.barge.proto.LogProto.Membership, org.robotninjas.barge.proto.LogProto.Membership.Builder, org.robotninjas.barge.proto.LogProto.MembershipOrBuilder> 
          getMembershipFieldBuilder() {
        if (membershipBuilder_ == null) {
          membershipBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robotninjas.barge.proto.LogProto.Membership, org.robotninjas.barge.proto.LogProto.Membership.Builder, org.robotninjas.barge.proto.LogProto.MembershipOrBuilder>(
                  membership_,
                  getParentForChildren(),
                  isClean());
          membership_ = null;
        }
        return membershipBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:JournalEntry)
    }

    static {
      defaultInstance = new JournalEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JournalEntry)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Append_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Append_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Membership_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Membership_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JournalEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JournalEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tlog.proto\032\013entry.proto\".\n\006Append\022\r\n\005in" +
      "dex\030\001 \002(\003\022\025\n\005entry\030\002 \002(\0132\006.Entry\":\n\nMemb" +
      "ership\022\r\n\005index\030\001 \002(\003\022\014\n\004term\030\002 \002(\003\022\017\n\007m" +
      "embers\030\003 \003(\t\"\216\001\n\014JournalEntry\022 \n\004type\030\001 " +
      "\002(\0162\022.JournalEntry.Type\022\027\n\006append\030\002 \001(\0132" +
      "\007.Append\022\037\n\nmembership\030\003 \001(\0132\013.Membershi" +
      "p\"\"\n\004Type\022\n\n\006APPEND\020\001\022\016\n\nMEMBERSHIP\020\002B\'\n" +
      "\033org.robotninjas.barge.protoB\010LogProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Append_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Append_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Append_descriptor,
              new java.lang.String[] { "Index", "Entry", });
          internal_static_Membership_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Membership_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Membership_descriptor,
              new java.lang.String[] { "Index", "Term", "Members", });
          internal_static_JournalEntry_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_JournalEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JournalEntry_descriptor,
              new java.lang.String[] { "Type", "Append", "Membership", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robotninjas.barge.proto.RaftEntry.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
